//
//  RecentSearchesInteractor.swift
//  weather-app
//
//  Created Ming Chu on 22/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecentSearchesInteractor: RecentSearchesInteractorInputProtocol {

    weak var presenter: RecentSearchesInteractorOutputProtocol?

    private let searchHistoryManager: SearchHistoryManager

    init(searchHistoryManager: SearchHistoryManager = .shared) {
        self.searchHistoryManager = searchHistoryManager
    }
    
    func requestFetchHistoryService() {
        let records = searchHistoryManager.getAllRecords()
        self.presenter?.fetchSearchHistoryDidSuccess(records: records)
    }

    func removeSearchRecord(record: SearchRecord) {
        self.searchHistoryManager.removeRecord(record: record)
    }

    func removeAllSearchRecord() {
        self.searchHistoryManager.cleanRecords()
    }

    
}
