//
//  RecentSearchesViewController.swift
//  weather-app
//
//  Created Ming Chu on 22/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecentSearchesViewController: UIViewController {

    @IBOutlet private weak var tableView: UITableView?

    @IBAction func closeButtonDidPressed(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }

    var presenter: RecentSearchesPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()

        self.setupInterface()

        self.presenter?.requestFetchSearchHistory()
    }

    private func setupInterface() {
        self.tableView?.dataSource = self
        self.tableView?.delegate = self
    }
}

extension RecentSearchesViewController: RecentSearchesViewProtocol {
    func updateSearchHistory(records: [SearchRecord]) {
        self.tableView?.reloadData()
    }
}

extension RecentSearchesViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.presenter?.searchRecords.count ?? 0
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let record = self.presenter?.searchRecords[indexPath.row] else { return UITableViewCell() }

        let cell = UITableViewCell()
        cell.backgroundColor = .red
        cell.textLabel?.text = record.searchType
        return cell
    }
}

extension RecentSearchesViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
}
