//
//  RecentSearchesPresenter.swift
//  weather-app
//
//  Created Ming Chu on 22/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecentSearchesPresenter: RecentSearchesPresenterProtocol, RecentSearchesInteractorOutputProtocol {

    weak private var view: RecentSearchesViewProtocol?
    var interactor: RecentSearchesInteractorInputProtocol?
    private let router: RecentSearchesWireframeProtocol

    init(interface: RecentSearchesViewProtocol, interactor: RecentSearchesInteractorInputProtocol?, router: RecentSearchesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
