//
//  RecentSearchesInteractor.swift
//  weather-app
//
//  Created Ming Chu on 22/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecentSearchesInteractor: RecentSearchesInteractorInputProtocol {

    weak var presenter: RecentSearchesInteractorOutputProtocol?
}
