//
//  RecentSearchesProtocols.swift
//  weather-app
//
//  Created Ming Chu on 22/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RecentSearchesWireframeProtocol: class {

}
//MARK: Presenter -
protocol RecentSearchesPresenterProtocol: class {

    var interactor: RecentSearchesInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol RecentSearchesInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol RecentSearchesInteractorInputProtocol: class {

    var presenter: RecentSearchesInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol RecentSearchesViewProtocol: class {

    var presenter: RecentSearchesPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
