//
//  RecentSearchesViewController.swift
//  weather-app
//
//  Created Ming Chu on 22/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecentSearchesViewController: UIViewController, RecentSearchesViewProtocol {

    @IBOutlet private weak var tableView: UITableView?

    @IBAction func closeButtonDidPressed(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }

    var presenter: RecentSearchesPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()

        self.setupInterface()
    }

    private func setupInterface() {
        self.tableView?.dataSource = self
        self.tableView?.delegate = self
    }
}

extension RecentSearchesViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return UITableViewCell()
    }
}

extension RecentSearchesViewController: UITableViewDelegate {

}
