//
//  RecentSearchesProtocols.swift
//  weather-app
//
//  Created Ming Chu on 22/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RecentSearchesWireframeProtocol: class {

}
//MARK: Presenter -
protocol RecentSearchesPresenterProtocol: class {

    var interactor: RecentSearchesInteractorInputProtocol? { get set }

    func requestFetchSearchHistory()
    func removeSearchRecord(record: SearchRecord)
    func removeAllSearchRecord()
}

//MARK: Interactor -
protocol RecentSearchesInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func fetchSearchHistoryDidSuccess(records: [SearchRecord])
    func fetchSearchHistoryDidFailed(error: Error?)
}

protocol RecentSearchesInteractorInputProtocol: class {

    var presenter: RecentSearchesInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func requestFetchHistoryService()
}

//MARK: View -
protocol RecentSearchesViewProtocol: class {

    var presenter: RecentSearchesPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func updateSearchHistory(records: [SearchRecord])
}
