//
//  WeatherRouter.swift
//  weather-app
//
//  Created Ming Chu on 20/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherRouter: WeatherWireframeProtocol {

    weak var viewController: UIViewController?

    private var openSettingsAlertActionSheet: UIAlertController {
        let message = "Need GPS permisson to perform GPS search, config it now?"
        let alert = UIAlertController(title: nil, message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { [weak self] (action) in
            self?.presentAppSettings()
        }))
        alert.addAction(UIAlertAction.init(title: "Cancel", style: .cancel, handler: nil))
        return alert
    }


    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = WeatherViewController(nibName: nil, bundle: nil)
        let interactor = WeatherInteractor()
        let router = WeatherRouter()
        let presenter = WeatherPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }

    private func presentAppSettings() {
        if let appSettings = URL(string: UIApplication.openSettingsURLString) {
            UIApplication.shared.open(appSettings, options: [:], completionHandler: nil)
        }
    }

    // MARK: - WeatherWireframeProtocol
    func presentOpenAppSettingsConfirmation() {
        self.viewController?.present(openSettingsAlertActionSheet, animated: true, completion: nil)
    }
}
