//
//  WeatherViewController.swift
//  weather-app
//
//  Created Ming Chu on 20/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherViewController: UIViewController {
    
    @IBOutlet private weak var searchBar: UISearchBar?
    @IBOutlet private weak var weatherWidgetView: UIView?
    @IBOutlet private weak var cityNameLabel: UILabel?
    @IBOutlet private weak var weatherDescriptionLabel: UILabel?
    @IBOutlet private weak var weatherIconImageView: UIImageView?
    @IBOutlet private weak var temperatureLabel: UILabel?
    @IBOutlet private weak var windValueLabel: UILabel?
    @IBOutlet private weak var humidityValueLabel: UILabel?
    @IBOutlet private weak var pressureValueLabel: UILabel?

	var presenter: WeatherPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension WeatherViewController: WeatherViewProtocol {
    func updateCurrentWeather() {
        //TODO: update UI
    }

    func showError(errorMessage: String) {
        //TODO: show error
    }
}
