//
//  WeatherInteractor.swift
//  weather-app
//
//  Created Ming Chu on 20/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherInteractor: WeatherInteractorInputProtocol {

    weak var presenter: WeatherInteractorOutputProtocol?

    func fetchCurrentWeather(queryType: QueryType) {
        //TODO: get api from WebService

        //api.openweathermap.org/data/2.5/weather?q={city name}
        //api.openweathermap.org/data/2.5/weather?zip={zip code}
        //api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}

        presenter?.fetchCurrentWeatherDidSuccess(data: "TODO:")
    }

}



//TODO: move it to WebService later
enum QueryType {
    /**
    get weather by ZIP code

    Examples of API calls:
    ```
    api.openweathermap.org/data/2.5/weather?q=London
    ```
     */
    case cityName(name: String)

    /**
    get weather by ZIP code

    Examples of API calls:
    ```
    api.openweathermap.org/data/2.5/weather?zip=94040
    ```
     */
    case zipCode(code: Int)

    /**
    get weather by geographic coordinates

    Examples of API calls:
    ```
    api.openweathermap.org/data/2.5/weather?lat=35&lon=139
    ```
     */
    case coordinates(lat: Double, lon: Double)
}
