//
//  WeatherInteractor.swift
//  weather-app
//
//  Created Ming Chu on 20/11/2019.
//  Copyright © 2019 vegantell. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherInteractor: WeatherInteractorInputProtocol {

    weak var presenter: WeatherInteractorOutputProtocol?

    func fetchCurrentWeather(queryType: QueryType) {
        //TODO: get api from WebService

        //api.openweathermap.org/data/2.5/weather?q={city name}
        //api.openweathermap.org/data/2.5/weather?zip={zip code}
        //api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}

        WebServiceManager.shared.request(params: queryType.params, completion: handler)
    }

    private var handler: WebServiceCompletionHandler<WeatherResponse> {
        return { [weak self] (response, error) in
            if let error = error {
                self?.presenter?.fetchCurrentWeatherDidFailed(error: error)
            } else if let response = response {
                self?.presenter?.fetchCurrentWeatherDidSuccess(weatherResponse: response)
            }
        }
    }
}
